# ============================================
# 1. Task Description
# Visualize a 100‑step random walk using matplotlib. The random walk
# is generated by updating the current position based on dice rolls,
# and the resulting list (random_walk) is plotted as a simple line
# chart. When a single list is passed to plt.plot(), matplotlib uses
# the list index as the x-axis and the list values as the y-axis.
#
# 2. Topics Covered
# - Generating a random walk with NumPy
# - Appending values to a Python list
# - Line plotting with matplotlib (plt.plot)
# - Understanding default x-axis behavior when passing one list
# ============================================

# 3. Python Script

# NumPy is imported and seed is set elsewhere in the environment

# Initialization of the walk
random_walk = [0]

# Build the random walk
for x in range(100):
    step = random_walk[-1]        # current position
    dice = np.random.randint(1, 7)

    if dice <= 2:
        step = max(0, step - 1)   # step down, but not below 0
    elif dice <= 5:
        step = step + 1           # step up by 1
    else:
        step = step + np.random.randint(1, 7)  # random upward jump

    random_walk.append(step)

# Import matplotlib for visualization
import matplotlib.pyplot as plt

# Plot the random walk (x-axis = index, y-axis = step value)
plt.plot(random_walk)

# Display the plot
plt.show()

# ============================================
# 4. Additional Notes
# - Passing a single argument to plt.plot(list) maps:
#       x-axis → list indices (0, 1, 2, ...)
#       y-axis → list values
# - You can improve readability with:
#       plt.xlabel("Step Number")
#       plt.ylabel("Position")
#       plt.title("Random Walk Simulation")
# - This visualization is the foundation for later exercises where
#   you'll generate *multiple* walks and analyze their distribution.
# ============================================
